# Generated by Django 2.2.6 on 2020-06-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200603_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
