# Generated by Django 2.2.6 on 2020-06-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
