# Generated by Django 2.2.6 on 2020-06-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200603_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default=None, max_length=200, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(default=None, verbose_name='date published')),
            ],
        ),
    ]
