# Generated by Django 2.2.6 on 2020-06-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200604_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='topic',
            new_name='course',
        ),
    ]
